plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hastagaming.arcmux'
    compileSdk 34


    options {
            aaptOptions {
                namespaced = true
            }
      }
    defaultConfig {
        applicationId "com.hastagaming.arcmux"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0-alpha"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
configurations.all {
    resolutionStrategy.forcedModules = ['com.android.tools.build:aapt2:8.2.0-10154469']
}
